/* Generated by AN DISI Unibo */ 
package it.unibo.dbwrapper

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.dbdriver.*

class Dbwrapper ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
		        val wrapper = Wrapper()
		        lateinit var CurrProduct : Product
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: STARTING...")
						CommUtils.outyellow("$name: initialization complete")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: waiting...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="getproductweight",cond=whenRequest("getProductWeight"))
					transition(edgeName="t01",targetState="getfreeslot",cond=whenRequest("getFreeSlot"))
					transition(edgeName="t02",targetState="getallproducts",cond=whenRequest("getAllProducts"))
					transition(edgeName="t03",targetState="getallslots",cond=whenRequest("getAllSlots"))
					transition(edgeName="t04",targetState="getloadedweight",cond=whenRequest("getLoadedWeight"))
					transition(edgeName="t05",targetState="updatehold",cond=whenDispatch("updateHold"))
				}	 
				state("getproductweight") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("getProductWeight(PID)"), Term.createTerm("getProductWeight(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val PID = payloadArg(0).toInt()
								                CurrProduct = wrapper.getProduct(PID)
								if(  !CurrProduct.getName().equals("NOT_FOUND")  
								 ){ 
												  val ProdWeight = CurrProduct.getWeight()
								answer("getProductWeight", "productWeight", "productWeight($ProdWeight)"   )  
								}
								else
								 {answer("getProductWeight", "productWeight", "productWeight(0)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("getfreeslot") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("getFreeSlot(V)"), Term.createTerm("getFreeSlot(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val FreeSlot = wrapper.getFirstAvailableSlot()
								answer("getFreeSlot", "freeSlot", "freeSlot($FreeSlot)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("getallproducts") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("getAllProducts(V)"), Term.createTerm("getAllProducts(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var ProductsList = wrapper.getAllProducts()  
								answer("getAllProducts", "allProducts", "allProducts($ProductsList)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("getallslots") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("getAllSlots(V)"), Term.createTerm("getAllSlots(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var SlotsList = wrapper.getAllSlots()  
								answer("getAllSlots", "slotsList", "slotsList($SlotsList)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("getloadedweight") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("getLoadedWeight(V)"), Term.createTerm("getLoadedWeight(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
									    		var slotsList = wrapper.getAllSlots()
									    		
									    		var LoadedWeight = 0.0
									    		for(slot in slotsList) {
									    			var PID = slot.getPID()
									    			if(PID > 0) {
										    			var product = wrapper.getProduct(PID)
										    			LoadedWeight += product.getWeight()
										    		}
									    		}
								answer("getLoadedWeight", "loadedWeight", "loadedWeight($LoadedWeight)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("updatehold") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("updateHold(Slot,PID)"), Term.createTerm("updateHold(Slot,PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            val slotNumber = payloadArg(0).toInt()
									            val pid = payloadArg(1).toInt()
									            val res = wrapper.loadProduct(pid)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
} 
