/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.planner.*
import main.java.planner.HoldMap.*

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val planner = PlannerForHold()
				val STEP = 170
				var Slot = 0
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: STARTING...")
						
									planner.initRobotState()
									HoldMapLoader.fromTextToBinFile("./HoldMap.txt");
									planner.loadMap("./HoldMap.bin")
						CommUtils.outgreen("$name: engaging BasicRobot...")
						request("engage", "engage(cargorobot,$STEP)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="engagedone",cond=whenReply("engagedone"))
					transition(edgeName="t016",targetState="engagerefused",cond=whenReply("engagerefused"))
				}	 
				state("engagedone") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: initialization complete")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("engagerefused") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: engage failed")
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: idle at home...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="movetoioport",cond=whenRequest("doDelivery"))
				}	 
				state("movetoioport") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: moving to ioport...")
						
									val target = planner.getCellCoordsByType(CellType.IOPORT)
									val Path = planner.findPath(target[0], target[1])
									planner.doPath(Path)
						request("doplan", "doplan($Path,$STEP)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t118",targetState="movetoslot",cond=whenReply("doplandone"))
					transition(edgeName="t119",targetState="pathfailure",cond=whenReply("doplanfailed"))
				}	 
				state("movetoslot") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: loading container...")
						delay(2000) 
						CommUtils.outgreen("$name: moving to slot...")
						
									var code = (Slot + 64).toChar()
									var type = CellType.fromCode("" + code)
									val target = planner.getCellCoordsByType(type)
									val Path = planner.findPath(target[0], target[1])
									planner.doPath(Path)
						request("doplan", "doplan($Path,$STEP)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t220",targetState="movebackhome",cond=whenReply("doplandone"))
					transition(edgeName="t221",targetState="pathfailure",cond=whenReply("doplanfailed"))
				}	 
				state("movebackhome") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: leaving container...")
						delay(2000) 
						CommUtils.outgreen("$name: moving back home...")
						
									val target = planner.getCellCoordsByType(CellType.HOME)
									val Path = planner.findPath(target[0], target[1])
									planner.doPath(Path)
						request("doplan", "doplan($Path,$STEP)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t322",targetState="reply",cond=whenReply("doplandone"))
					transition(edgeName="t323",targetState="trapped",cond=whenReply("doplanfailed"))
				}	 
				state("reply") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: home sweet home")
						answer("doDelivery", "deliveryDone", "deliveryDone(1)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("pathfailure") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: path failure, trying to go back home")
						delay(700) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="movebackhome", cond=doswitch() )
				}	 
				state("trapped") { //this:State
					action { //it:State
						CommUtils.outgreen("$name: help, I'm trapped!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
